# fly.toml app configuration file generated for githook-sh on 2025-12-18T22:58:29-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'githook-sh'
primary_region = 'ord'

[build]

[deploy]
  strategy = 'bluegreen'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 6
  auto_assign_hostname = false

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '5s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
